# Generated by Django 5.1 on 2025-12-05 16:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stamprally',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(max_length=2000, verbose_name='Description')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('required_stamps', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)], verbose_name='Required Stamps')),
                ('prize_description', models.TextField(max_length=1000, verbose_name='Prize Description')),
                ('prize_image', models.ImageField(blank=True, null=True, upload_to='stampralley/prizes/', verbose_name='Prize Image')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='stampralley/banners/', verbose_name='Banner Image')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Participants')),
            ],
            options={
                'verbose_name': 'Stamp Rally',
                'verbose_name_plural': 'Stamp Rallies',
                'db_table': 'stampralley',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerStamprally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('prize_received', models.BooleanField(default=False, verbose_name='Prize Received')),
                ('prize_received_at', models.DateTimeField(blank=True, null=True, verbose_name='Prize Received At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamprally_participations', to=settings.AUTH_USER_MODEL)),
                ('stamprally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='campaigns.stamprally')),
            ],
            options={
                'db_table': 'customer_stamprally',
                'ordering': ['-joined_at'],
                'unique_together': {('customer', 'stamprally')},
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('card_type', models.CharField(choices=[('discount_percent', 'Discount Percentage'), ('discount_amount', 'Discount Amount'), ('free_item', 'Free Item')], max_length=20, verbose_name='Card Type')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount Percentage')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Discount Amount')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Price')),
                ('valid_from', models.DateTimeField(verbose_name='Valid From')),
                ('valid_until', models.DateTimeField(verbose_name='Valid Until')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Minimum Purchase Amount')),
                ('max_uses_per_customer', models.PositiveIntegerField(default=1, verbose_name='Max Uses Per Customer')),
                ('total_available', models.PositiveIntegerField(help_text='Total number of gift cards available for purchase', verbose_name='Total Available')),
                ('image', models.ImageField(blank=True, null=True, upload_to='giftcards/', verbose_name='Card Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('applicable_restaurants', models.ManyToManyField(blank=True, related_name='applicable_giftcards', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Gift Card',
                'verbose_name_plural': 'Gift Cards',
                'db_table': 'giftcards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WinPrize',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prize_description', models.TextField(verbose_name='Prize Description')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Awarded At')),
                ('delivered', models.BooleanField(default=False, verbose_name='Delivered')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Tracking Number')),
                ('customer_stamprally', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prize', to='campaigns.customerstamprally')),
            ],
            options={
                'verbose_name': 'Win Prize',
                'verbose_name_plural': 'Win Prizes',
                'db_table': 'win_prizes',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='MyGiftCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Gift Card Code')),
                ('status', models.CharField(choices=[('unused', 'Unused'), ('used', 'Used'), ('expired', 'Expired')], default='unused', max_length=20, verbose_name='Status')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Purchased At')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Purchase Price')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used At')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='giftcards/qr/', verbose_name='QR Code')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_giftcards', to=settings.AUTH_USER_MODEL)),
                ('giftcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_giftcards', to='campaigns.giftcard')),
                ('used_at_restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_giftcards', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'My Gift Card',
                'verbose_name_plural': 'My Gift Cards',
                'db_table': 'my_giftcards',
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='my_giftcard_custome_52e51f_idx'), models.Index(fields=['code'], name='my_giftcard_code_71954c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stamped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamped_at', models.DateTimeField(auto_now_add=True, verbose_name='Stamped At')),
                ('customer_stamprally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to='campaigns.customerstamprally')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_stamps', to='restaurants.restaurant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_stamps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stamped',
                'ordering': ['stamped_at'],
                'unique_together': {('customer_stamprally', 'restaurant')},
            },
        ),
        migrations.CreateModel(
            name='JoinShops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_stampralley', to='restaurants.restaurant')),
                ('stamprally', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_shops', to='campaigns.stamprally')),
            ],
            options={
                'db_table': 'stamprally_join_shops',
                'ordering': ['display_order', 'id'],
                'unique_together': {('stamprally', 'restaurant')},
            },
        ),
    ]
