# Generated by Django 5.1 on 2025-12-05 16:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Template Name')),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('restaurant_approved', 'Restaurant Approved'), ('restaurant_rejected', 'Restaurant Rejected'), ('review_moderated', 'Review Moderated'), ('giftcard_purchased', 'Gift Card Purchased'), ('stamprally_completed', 'Stamp Rally Completed'), ('prize_won', 'Prize Won'), ('newsletter', 'Newsletter')], max_length=30, unique=True, verbose_name='Template Type')),
                ('subject', models.CharField(max_length=200, verbose_name='Email Subject')),
                ('html_body', models.TextField(verbose_name='HTML Body')),
                ('text_body', models.TextField(blank=True, verbose_name='Text Body')),
                ('variables_help', models.TextField(blank=True, help_text='Document template variables like {{user_name}}, {{restaurant_name}}', verbose_name='Available Variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'email_templates',
                'ordering': ['template_type'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_reviews', models.BooleanField(default=True, verbose_name='Email - Reviews')),
                ('email_campaigns', models.BooleanField(default=True, verbose_name='Email - Campaigns')),
                ('email_system', models.BooleanField(default=True, verbose_name='Email - System')),
                ('push_reviews', models.BooleanField(default=True, verbose_name='Push - Reviews')),
                ('push_campaigns', models.BooleanField(default=True, verbose_name='Push - Campaigns')),
                ('push_system', models.BooleanField(default=True, verbose_name='Push - System')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Recipient Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('opened', models.BooleanField(default=False, verbose_name='Opened')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Opened At')),
                ('clicked', models.BooleanField(default=False, verbose_name='Clicked')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Clicked At')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_emails', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='notifications.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_email', '-created_at'], name='email_logs_recipie_d24bb8_idx'), models.Index(fields=['status'], name='email_logs_status_e3be55_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('general', 'General'), ('review_reply', 'Review Reply'), ('stamprally', 'Stamp Rally'), ('giftcard', 'Gift Card'), ('promotion', 'Promotion')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('message', models.TextField(max_length=500, verbose_name='Message')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='Action URL')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Additional Data')),
                ('sent', models.BooleanField(default=False, verbose_name='Sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Notification',
                'verbose_name_plural': 'Push Notifications',
                'db_table': 'push_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='push_notifi_recipie_fd06c8_idx'), models.Index(fields=['read'], name='push_notifi_read_d2b7f3_idx')],
            },
        ),
    ]
