# Generated by Django 5.1 on 2025-12-05 16:21

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Cuisine Type')),
                ('name_en', models.CharField(blank=True, max_length=50, verbose_name='Cuisine Type (English)')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='cuisines/', verbose_name='Icon')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Cuisine',
                'verbose_name_plural': 'Cuisines',
                'db_table': 'cuisines',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Restaurant Name')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Restaurant Name (English)')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, max_length=2000, verbose_name='Description (English)')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='JP', unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Restaurant Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('line_id', models.CharField(blank=True, max_length=100, verbose_name='LINE ID')),
                ('postal_code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{3}-?\\d{4}$')], verbose_name='Postal Code')),
                ('prefecture', models.CharField(max_length=20, verbose_name='Prefecture')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address_line', models.CharField(max_length=200, verbose_name='Address Line')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='Building')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='Longitude')),
                ('opening_time', models.TimeField(verbose_name='Opening Time')),
                ('closing_time', models.TimeField(verbose_name='Closing Time')),
                ('seating_capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Seating Capacity')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Parking Available')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='WiFi Available')),
                ('is_smoking_allowed', models.BooleanField(default=False, verbose_name='Smoking Allowed')),
                ('accepts_reservations', models.BooleanField(default=True, verbose_name='Accepts Reservations')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/', verbose_name='Logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='restaurants/covers/', verbose_name='Cover Image')),
                ('interior_image1', models.ImageField(blank=True, null=True, upload_to='restaurants/interiors/', verbose_name='Interior Image 1')),
                ('interior_image2', models.ImageField(blank=True, null=True, upload_to='restaurants/interiors/', verbose_name='Interior Image 2')),
                ('interior_image3', models.ImageField(blank=True, null=True, upload_to='restaurants/interiors/', verbose_name='Interior Image 3')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('is_visible', models.BooleanField(default=False, help_text='Show restaurant on map and search', verbose_name='Visible to Public')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Total Reviews')),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Average Rating')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Total Views')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_restaurants', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'db_table': 'restaurants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Product Name (English)')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, max_length=1000, verbose_name='Description (English)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Image')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['restaurant', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClosedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday'), ('holiday', 'Holiday')], max_length=10, verbose_name='Day of Week')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_days', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Closed Day',
                'verbose_name_plural': 'Closed Days',
                'db_table': 'restaurant_closed_days',
            },
        ),
        migrations.CreateModel(
            name='RestaurantCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary Cuisine')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_cuisines', to='restaurants.cuisine')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_cuisines', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'restaurant_cuisines',
            },
        ),
        migrations.CreateModel(
            name='RestaurantView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='restaurants.restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restaurant View',
                'verbose_name_plural': 'Restaurant Views',
                'db_table': 'restaurant_views',
            },
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['name'], name='restaurants_name_cc4837_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['status'], name='restaurants_status_7a5ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['prefecture', 'city'], name='restaurants_prefect_71591e_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['latitude', 'longitude'], name='restaurants_latitud_bff9f0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['restaurant', 'is_available'], name='products_restaur_a5eee8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='closedday',
            unique_together={('restaurant', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='restaurantcuisine',
            unique_together={('restaurant', 'cuisine')},
        ),
        migrations.AlterUniqueTogether(
            name='restaurantview',
            unique_together={('restaurant', 'user')},
        ),
    ]
