# Generated by Django 5.1 on 2025-12-05 16:21

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('user_type', models.IntegerField(choices=[(1, 'Customer'), (2, 'Restaurant'), (3, 'Admin')], db_index=True, default=1, verbose_name='User Type')),
                ('oidc_subject', models.CharField(blank=True, help_text='Keycloak user ID', max_length=255, null=True, unique=True, verbose_name='OIDC Subject (sub)')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Password Changed At')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('customer_number', models.CharField(db_index=True, default=apps.accounts.models.generate_customer_number, max_length=12, unique=True, verbose_name='Customer Number')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Japanese phone number format', max_length=128, region='JP', unique=True, verbose_name='Phone Number')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('postal_code', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid postal code (e.g., 123-4567)', regex='^\\d{3}-?\\d{4}$')], verbose_name='Postal Code')),
                ('prefecture', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prefecture')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('address_line', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Line')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/customers/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio')),
                ('language', models.CharField(choices=[('ja', 'Japanese'), ('en', 'English')], default='ja', max_length=5, verbose_name='Preferred Language')),
                ('receive_newsletter', models.BooleanField(default=True, verbose_name='Receive Newsletter')),
                ('receive_push_notifications', models.BooleanField(default=True, verbose_name='Receive Push Notifications')),
                ('is_active', models.BooleanField(default=True, help_text='Account active status', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'db_table': 'customer_profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_number'], name='customer_pr_custome_d86675_idx'), models.Index(fields=['phone_number'], name='customer_pr_phone_n_488511_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type'], name='users_user_ty_578f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['oidc_subject'], name='users_oidc_su_311b56_idx'),
        ),
    ]
