# Generated by Django 5.1 on 2025-12-06 13:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=200, verbose_name='Organization Name')),
                ('slug', models.SlugField(default='tabitabe', unique=True, verbose_name='Slug')),
                ('default_currency', models.CharField(default='JPY', max_length=3, verbose_name='Default Currency')),
                ('supported_currencies', models.JSONField(default=list, help_text='List of supported currency codes (e.g., ["JPY", "USD", "VND"])', verbose_name='Supported Currencies')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#FF6B6B', max_length=7, verbose_name='Primary Color')),
                ('support_email', models.EmailField(default='support@tabitabe.com', max_length=254, verbose_name='Support Email')),
                ('support_phone', models.CharField(blank=True, max_length=20, verbose_name='Support Phone')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organization',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Customer'), (2, 'Restaurant'), (3, 'Admin')], db_index=True, help_text='DEPRECATED: Use roles instead. Will be removed in v2.0', null=True, verbose_name='User Type (DEPRECATED)'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('resource', models.CharField(choices=[('organization', 'Organization Settings'), ('region', 'Region Management'), ('role', 'Role Management'), ('user', 'User Management'), ('restaurant', 'Restaurant'), ('review', 'Review'), ('campaign', 'Campaign'), ('government_campaign', 'Government Campaign'), ('advertisement', 'Advertisement'), ('badge', 'Badge'), ('leaderboard', 'Leaderboard'), ('checkin', 'Check-in'), ('analytics', 'Analytics'), ('financial', 'Financial Reports'), ('audit_log', 'Audit Log')], max_length=50, verbose_name='Resource')),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('approve', 'Approve'), ('moderate', 'Moderate'), ('export', 'Export Data'), ('assign', 'Assign')], max_length=20, verbose_name='Action')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('requires_global_scope', models.BooleanField(default=False, help_text='If True, permission requires GLOBAL scope level', verbose_name='Requires Global Scope')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
                'ordering': ['resource', 'action'],
                'indexes': [models.Index(fields=['resource', 'action'], name='permissions_resourc_2eec83_idx')],
                'unique_together': {('resource', 'action')},
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Region Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Region Code')),
                ('default_language', models.CharField(default='ja', max_length=10, verbose_name='Default Language')),
                ('timezone', models.CharField(default='Asia/Tokyo', max_length=50, verbose_name='Timezone')),
                ('currency', models.CharField(default='JPY', max_length=3, verbose_name='Currency')),
                ('cloudfront_distribution', models.CharField(blank=True, help_text='AWS CloudFront distribution for this region', max_length=100, verbose_name='CloudFront Distribution ID')),
                ('s3_bucket_region', models.CharField(default='ap-northeast-1', max_length=50, verbose_name='S3 Bucket Region')),
                ('support_email', models.EmailField(max_length=254, verbose_name='Support Email')),
                ('support_phone', models.CharField(blank=True, max_length=20, verbose_name='Support Phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('launched_at', models.DateField(blank=True, null=True, verbose_name='Launch Date')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'regions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Market Name')),
                ('code', models.CharField(max_length=20, verbose_name='Market Code')),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Market center latitude', max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Market center longitude', max_digits=11, verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='accounts.region')),
            ],
            options={
                'verbose_name': 'Market',
                'verbose_name_plural': 'Markets',
                'db_table': 'markets',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(choices=[('super_admin', 'Super Admin'), ('global_operations', 'Global Operations Manager'), ('region_admin', 'Regional Admin'), ('restaurant_approval_specialist', 'Restaurant Approval Specialist'), ('content_moderator', 'Content Moderator'), ('customer_support_agent', 'Customer Support Agent'), ('campaign_manager', 'Campaign Manager'), ('government_admin', 'Government Administrator'), ('government_analyst', 'Government Analyst'), ('restaurant_owner', 'Restaurant Owner'), ('restaurant_manager', 'Restaurant Manager'), ('restaurant_staff', 'Restaurant Staff'), ('restaurant_viewer', 'Restaurant Viewer'), ('advertiser_enterprise', 'Enterprise Advertiser'), ('advertiser_premium', 'Premium Advertiser'), ('advertiser_basic', 'Basic Advertiser'), ('customer_premium_plus', 'Premium Plus Customer'), ('customer_premium', 'Premium Customer'), ('customer_free', 'Free Customer')], max_length=50, unique=True, verbose_name='Role Name')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('scope_level', models.CharField(choices=[('global', 'Global'), ('region', 'Regional'), ('market', 'Market'), ('entity', 'Entity')], default='entity', help_text='Defines the access scope for this role', max_length=20, verbose_name='Scope Level')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_system_role', models.BooleanField(default=True, help_text='System roles cannot be deleted', verbose_name='System Role')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='accounts.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('expires_at', models.DateTimeField(blank=True, help_text='If set, role will expire after this date', null=True, verbose_name='Expires At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_roles', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(blank=True, help_text='Required if role scope is MARKET', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.market')),
                ('region', models.ForeignKey(blank=True, help_text='Required if role scope is REGION or MARKET', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.region')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'user_roles',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='User roles (RBAC)', related_name='users', through='accounts.UserRole', to='accounts.role'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['code'], name='regions_code_aa1ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['is_active'], name='regions_is_acti_dadff5_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['region', 'is_active'], name='markets_region__b8d882_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['code'], name='markets_code_08a064_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='market',
            unique_together={('region', 'code')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='roles_name_a96913_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_active'], name='roles_is_acti_723ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_active'], name='user_roles_user_id_4ec42c_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'region'], name='user_roles_role_id_1b28af_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['expires_at'], name='user_roles_expires_aafda2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'region', 'market')},
        ),
    ]
