# Generated by Django 5.1 on 2025-12-06 13:12

from django.db import migrations


def seed_organization(apps, schema_editor):
    """Create default organization"""
    Organization = apps.get_model('accounts', 'Organization')
    
    # Singleton organization
    Organization.objects.get_or_create(
        slug='tabitabe',
        defaults={
            'name': 'Tabitabe Inc.',
            'default_currency': 'JPY',
            'supported_currencies': ['JPY', 'USD', 'VND', 'THB'],
            'primary_color': '#FF6B6B',
            'support_email': 'support@tabitabe.com',
            'support_phone': '+81-3-1234-5678'
        }
    )


def seed_regions(apps, schema_editor):
    """Create default regions"""
    Organization = apps.get_model('accounts', 'Organization')
    Region = apps.get_model('accounts', 'Region')
    
    org = Organization.objects.first()
    if not org:
        return
    
    # Japan region
    Region.objects.get_or_create(
        code='JP',
        defaults={
            'organization': org,
            'name': 'Japan',
            'default_language': 'ja',
            'timezone': 'Asia/Tokyo',
            'currency': 'JPY',
            's3_bucket_region': 'ap-northeast-1',
            'support_email': 'support.jp@tabitabe.com',
            'support_phone': '+81-3-1234-5678',
            'is_active': True
        }
    )


def seed_permissions(apps, schema_editor):
    """Create all permissions"""
    Permission = apps.get_model('accounts', 'Permission')
    
    permissions_data = [
        # Organization permissions
        ('organization', 'view', 'View organization settings', False),
        ('organization', 'edit', 'Edit organization settings', True),
        
        # Region permissions
        ('region', 'view', 'View regions', False),
        ('region', 'create', 'Create new regions', True),
        ('region', 'edit', 'Edit regions', True),
        ('region', 'delete', 'Delete regions', True),
        
        # User permissions
        ('user', 'view', 'View users', False),
        ('user', 'create', 'Create users', False),
        ('user', 'edit', 'Edit users', False),
        ('user', 'delete', 'Delete users', True),
        
        # Restaurant permissions
        ('restaurant', 'view', 'View restaurants', False),
        ('restaurant', 'create', 'Create restaurants', False),
        ('restaurant', 'edit', 'Edit restaurants', False),
        ('restaurant', 'delete', 'Delete restaurants', True),
        ('restaurant', 'approve', 'Approve restaurant registrations', False),
        
        # Review permissions
        ('review', 'view', 'View reviews', False),
        ('review', 'create', 'Create reviews', False),
        ('review', 'edit', 'Edit reviews', False),
        ('review', 'delete', 'Delete reviews', False),
        ('review', 'moderate', 'Moderate reviews', False),
        
        # Campaign permissions
        ('campaign', 'view', 'View campaigns', False),
        ('campaign', 'create', 'Create campaigns', False),
        ('campaign', 'edit', 'Edit campaigns', False),
        ('campaign', 'delete', 'Delete campaigns', False),
        
        # Government campaign permissions
        ('government_campaign', 'view', 'View government campaigns', False),
        ('government_campaign', 'create', 'Create government campaigns', False),
        ('government_campaign', 'edit', 'Edit government campaigns', False),
        ('government_campaign', 'delete', 'Delete government campaigns', False),
        
        # Analytics permissions
        ('analytics', 'view', 'View analytics', False),
        ('analytics', 'export', 'Export analytics data', False),
        
        # Financial permissions
        ('financial', 'view', 'View financial reports', False),
        ('financial', 'export', 'Export financial data', True),
    ]
    
    for resource, action, description, requires_global in permissions_data:
        Permission.objects.get_or_create(
            resource=resource,
            action=action,
            defaults={
                'description': description,
                'requires_global_scope': requires_global
            }
        )


def seed_roles(apps, schema_editor):
    """Create all roles with permissions"""
    Role = apps.get_model('accounts', 'Role')
    Permission = apps.get_model('accounts', 'Permission')
    
    # Define roles with their permissions
    roles_config = {
        # Global Admin Roles
        'super_admin': {
            'display_name': 'Super Admin',
            'description': 'Full system access',
            'scope_level': 'global',
            'permissions': '*'  # All permissions
        },
        'global_operations': {
            'display_name': 'Global Operations Manager',
            'description': 'Manage operations across all regions',
            'scope_level': 'global',
            'permissions': [
                ('region', 'view'),
                ('user', 'view'), ('user', 'edit'),
                ('restaurant', 'view'), ('restaurant', 'edit'), ('restaurant', 'approve'),
                ('analytics', 'view'), ('analytics', 'export'),
            ]
        },
        
        # Regional Admin Roles
        'region_admin': {
            'display_name': 'Regional Admin',
            'description': 'Full access within assigned region',
            'scope_level': 'region',
            'permissions': [
                ('user', 'view'), ('user', 'create'), ('user', 'edit'),
                ('restaurant', 'view'), ('restaurant', 'edit'), ('restaurant', 'approve'),
                ('review', 'view'), ('review', 'moderate'),
                ('campaign', 'view'), ('campaign', 'create'), ('campaign', 'edit'),
                ('analytics', 'view'),
            ]
        },
        'restaurant_approval_specialist': {
            'display_name': 'Restaurant Approval Specialist',
            'description': 'Approve restaurant registrations',
            'scope_level': 'region',
            'permissions': [
                ('restaurant', 'view'), ('restaurant', 'approve'),
            ]
        },
        'content_moderator': {
            'display_name': 'Content Moderator',
            'description': 'Moderate user-generated content',
            'scope_level': 'region',
            'permissions': [
                ('review', 'view'), ('review', 'moderate'), ('review', 'delete'),
                ('restaurant', 'view'),
            ]
        },
        'customer_support_agent': {
            'display_name': 'Customer Support Agent',
            'description': 'Handle customer inquiries',
            'scope_level': 'region',
            'permissions': [
                ('user', 'view'), ('user', 'edit'),
                ('restaurant', 'view'),
                ('review', 'view'),
            ]
        },
        
        # Government Roles
        'government_admin': {
            'display_name': 'Government Administrator',
            'description': 'Manage government campaigns and view analytics',
            'scope_level': 'region',
            'permissions': [
                ('government_campaign', 'view'), ('government_campaign', 'create'), 
                ('government_campaign', 'edit'), ('government_campaign', 'delete'),
                ('restaurant', 'view'),
                ('analytics', 'view'), ('analytics', 'export'),
            ]
        },
        'government_analyst': {
            'display_name': 'Government Analyst',
            'description': 'View campaign analytics',
            'scope_level': 'region',
            'permissions': [
                ('government_campaign', 'view'),
                ('analytics', 'view'),
            ]
        },
        
        # Restaurant Roles
        'restaurant_owner': {
            'display_name': 'Restaurant Owner',
            'description': 'Full control of own restaurant',
            'scope_level': 'entity',
            'permissions': [
                ('restaurant', 'view'), ('restaurant', 'edit'),
                ('review', 'view'),
                ('campaign', 'view'),
            ]
        },
        'restaurant_manager': {
            'display_name': 'Restaurant Manager',
            'description': 'Manage restaurant operations',
            'scope_level': 'entity',
            'permissions': [
                ('restaurant', 'view'), ('restaurant', 'edit'),
                ('review', 'view'),
            ]
        },
        'restaurant_staff': {
            'display_name': 'Restaurant Staff',
            'description': 'Limited restaurant access',
            'scope_level': 'entity',
            'permissions': [
                ('restaurant', 'view'),
                ('review', 'view'),
            ]
        },
        'restaurant_viewer': {
            'display_name': 'Restaurant Viewer',
            'description': 'Read-only access to restaurant',
            'scope_level': 'entity',
            'permissions': [
                ('restaurant', 'view'),
            ]
        },
        
        # Customer Roles
        'customer_premium_plus': {
            'display_name': 'Premium Plus Customer',
            'description': 'Premium Plus subscription tier',
            'scope_level': 'entity',
            'permissions': [
                ('review', 'create'), ('review', 'edit'),
            ]
        },
        'customer_premium': {
            'display_name': 'Premium Customer',
            'description': 'Premium subscription tier',
            'scope_level': 'entity',
            'permissions': [
                ('review', 'create'), ('review', 'edit'),
            ]
        },
        'customer_free': {
            'display_name': 'Free Customer',
            'description': 'Free tier customer',
            'scope_level': 'entity',
            'permissions': [
                ('review', 'create'),
            ]
        },
    }
    
    # Create roles and assign permissions
    for role_name, config in roles_config.items():
        role, created = Role.objects.get_or_create(
            name=role_name,
            defaults={
                'display_name': config['display_name'],
                'description': config['description'],
                'scope_level': config['scope_level'],
                'is_active': True,
                'is_system_role': True
            }
        )
        
        if created or True:  # Always update permissions
            if config['permissions'] == '*':
                # Super admin gets all permissions
                role.permissions.set(Permission.objects.all())
            else:
                # Assign specific permissions
                perms = []
                for resource, action in config['permissions']:
                    try:
                        perm = Permission.objects.get(resource=resource, action=action)
                        perms.append(perm)
                    except Permission.DoesNotExist:
                        pass
                role.permissions.set(perms)


def reverse_seed(apps, schema_editor):
    """Remove seeded data (for rollback)"""
    Organization = apps.get_model('accounts', 'Organization')
    Region = apps.get_model('accounts', 'Region')
    Role = apps.get_model('accounts', 'Role')
    Permission = apps.get_model('accounts', 'Permission')
    
    # Delete in reverse order to respect foreign keys
    Role.objects.all().delete()
    Permission.objects.all().delete()
    Region.objects.all().delete()
    Organization.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_alter_customuser_user_type_permission_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_organization, reverse_seed),
        migrations.RunPython(seed_regions, migrations.RunPython.noop),
        migrations.RunPython(seed_permissions, migrations.RunPython.noop),
        migrations.RunPython(seed_roles, migrations.RunPython.noop),
    ]

