# Generated by Django 5.1 on 2025-12-06 13:16

from django.db import migrations


def migrate_users_to_rbac(apps, schema_editor):
    """
    Migrate existing users from user_type to RBAC roles
    Maps:
    - user_type=1 (CUSTOMER) → customer_free role
    - user_type=2 (RESTAURANT) → restaurant_owner role  
    - user_type=3 (ADMIN) → super_admin role
    """
    CustomUser = apps.get_model('accounts', 'CustomUser')
    Role = apps.get_model('accounts', 'Role')
    UserRole = apps.get_model('accounts', 'UserRole')
    
    # Get roles
    try:
        customer_free = Role.objects.get(name='customer_free')
        restaurant_owner = Role.objects.get(name='restaurant_owner')
        super_admin = Role.objects.get(name='super_admin')
    except Role.DoesNotExist as e:
        print(f"⚠️  Warning: Required role not found: {e}")
        print("Make sure 0003_seed_rbac_data migration ran successfully")
        return
    
    # Migrate users
    migrated_count = 0
    skipped_count = 0
    
    for user in CustomUser.objects.all():
        # Skip if user already has roles
        if UserRole.objects.filter(user=user).exists():
            skipped_count += 1
            continue
        
        # Determine role based on user_type
        role = None
        if user.user_type == 1:  # CUSTOMER
            role = customer_free
        elif user.user_type == 2:  # RESTAURANT
            role = restaurant_owner
        elif user.user_type == 3:  # ADMIN
            role = super_admin
        else:
            print(f"⚠️  User {user.email} has unknown user_type: {user.user_type}")
            continue
        
        # Create UserRole
        UserRole.objects.create(
            user=user,
            role=role,
            is_active=True
        )
        migrated_count += 1
        print(f"✅ Migrated {user.email} → {role.display_name}")
    
    print(f"\n📊 Migration Summary:")
    print(f"   - Migrated: {migrated_count} users")
    print(f"   - Skipped (already has roles): {skipped_count} users")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: Remove all RBAC role assignments
    Note: This won't restore user_type values
    """
    UserRole = apps.get_model('accounts', 'UserRole')
    
    deleted_count = UserRole.objects.all().count()
    UserRole.objects.all().delete()
    
    print(f"🔄 Reversed: Deleted {deleted_count} user role assignments")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_rbac_data'),
    ]

    operations = [
        migrations.RunPython(migrate_users_to_rbac, reverse_migration),
    ]
