# Generated by Django 5.1 on 2025-12-05 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push Notifications')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS Notifications')),
                ('marketing_emails', models.BooleanField(default=False, verbose_name='Marketing Emails')),
                ('newsletter', models.BooleanField(default=False, verbose_name='Newsletter')),
                ('show_reviews_publicly', models.BooleanField(default=True, verbose_name='Show Reviews Publicly')),
                ('share_location', models.BooleanField(default=False, verbose_name='Share Location')),
                ('language', models.CharField(choices=[('ja', 'Japanese'), ('en', 'English')], default='ja', max_length=10, verbose_name='Language')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Preference',
                'verbose_name_plural': 'Customer Preferences',
                'db_table': 'customer_preferences',
            },
        ),
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('activity_type', models.CharField(choices=[('restaurant_view', 'Restaurant View'), ('review_create', 'Review Created'), ('review_update', 'Review Updated'), ('favorite_add', 'Favorite Added'), ('favorite_remove', 'Favorite Removed'), ('giftcard_purchase', 'Gift Card Purchased'), ('giftcard_use', 'Gift Card Used'), ('stamprally_join', 'Stamp Rally Joined'), ('stamp_collect', 'Stamp Collected')], max_length=30, verbose_name='Activity Type')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_activities', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Customer Activity',
                'verbose_name_plural': 'Customer Activities',
                'db_table': 'customer_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='customer_ac_custome_3e95a4_idx'), models.Index(fields=['activity_type', '-created_at'], name='customer_ac_activit_95d4db_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('query', models.CharField(max_length=200, verbose_name='Search Query')),
                ('filters_used', models.JSONField(blank=True, default=dict, verbose_name='Filters Used')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='Results Count')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search History',
                'db_table': 'customer_search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='customer_se_custome_40767b_idx')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_restaurants', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Favorite Restaurant',
                'verbose_name_plural': 'Favorite Restaurants',
                'db_table': 'favorite_restaurants',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'restaurant')},
            },
        ),
    ]
